version: '3.8'

services:
  web:
    build: .
    container_name: my-links-page
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - cloud
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - 'traefik.enable=true'
      - 'traefik.http.routers.website.rule=Host(`s8e.in`)'
      - 'traefik.http.routers.website.entrypoints=websecure'
      - 'traefik.http.routers.website.tls.certresolver=cloudflare'
      - 'traefik.http.services.website.loadbalancer.server.port=80'

networks:
  cloud:
    external: true
